version: '3.7'

services:
  web:
    image: nginx
    depends_on:
      - php
    volumes:
      - ./configuration/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/code
    ports:
      - "80:80"
  php:
    build:
      context: php
    depends_on:
      - db
    volumes:
      - ./src:/code
  db:
    image: mariadb
    volumes:
    - ./src/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=blog_bdd
    - MYSQL_USER=amine
    - MYSQL_PASSWORD=ipssi
  adminer-nginx:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
